//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomanApp.Client.Mobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RomanApp.Client.Mobile.Resx.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry.
        /// </summary>
        internal static string No_Help_Header {
            get {
                return ResourceManager.GetString("No.Help.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, The document you are requests has not been found..
        /// </summary>
        internal static string No_Help_Line1 {
            get {
                return ResourceManager.GetString("No.Help.Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string Overview_About_Encrypted {
            get {
                return ResourceManager.GetString("Overview.About.Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the stored data encrypted?.
        /// </summary>
        internal static string Overview_About_Encrypted_Header {
            get {
                return ResourceManager.GetString("Overview.About.Encrypted.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    RomanApp is a tool to divide the expenses between all the guests in a current event.&lt;br /&gt;&lt;br /&gt;
        ///    In a scenario where some guests have contributed money for the event and some didn&apos;t, RomanApp will display the amounts of money that every guests, the ones who did not contributed enough, owe and the amount every guest should collect, the ones that contributed more than they have to.
        ///    .
        /// </summary>
        internal static string Overview_About_What {
            get {
                return ResourceManager.GetString("Overview.About.What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is RomanApp?.
        /// </summary>
        internal static string Overview_About_What_Header {
            get {
                return ResourceManager.GetString("Overview.About.What.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    This app works completely offline. There is no need to have any Internet or LAN connection available to run it. It can run on &lt;strong&gt;Airplane Mode&lt;/strong&gt; if needed.&lt;br /&gt;&lt;br /&gt;
        ///    It will also store your progress locally so you can revisit your work at any time even after restarting your device.
        ///    .
        /// </summary>
        internal static string Overview_About_Work {
            get {
                return ResourceManager.GetString("Overview.About.Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        internal static string Overview_About_Work_Header {
            get {
                return ResourceManager.GetString("Overview.About.Work.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Overview_Header {
            get {
                return ResourceManager.GetString("Overview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview_Help_Topic {
            get {
                return ResourceManager.GetString("Overview.Help.Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An overall view about RomanApp..
        /// </summary>
        internal static string Overview_Help_Topic_Quick_Summary {
            get {
                return ResourceManager.GetString("Overview.Help.Topic.Quick.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      
        ///      This help will guide you through the app, trying to clear any doubts you may have about its purpose, usage and development. &lt;br /&gt;&lt;br /&gt;
        ///      You can access the Help at any moment by tapping the three dot menu at the top right corner of the screen and then tapping &quot;Help&quot;. This will open the Help view at the section you are currently working on.&lt;br /&gt;&lt;br /&gt;
        ///      For example if you access the Help while you were in the &lt;strong&gt;Settings&lt;/strong&gt; panel you will access the Settings section of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Overview_Summary {
            get {
                return ResourceManager.GetString("Overview.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also.
        /// </summary>
        internal static string See_Also {
            get {
                return ResourceManager.GetString("See.Also", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I add an element for my event?.
        /// </summary>
        internal static string Sheet_Input_Adding_Header {
            get {
                return ResourceManager.GetString("Sheet.Input.Adding.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    Notice that the second field will display a different label depending of the type of element that you are adding:&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; &quot;Contribution&quot; if you are adding a &lt;strong&gt;Guest&lt;/strong&gt;.&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; &quot;Value&quot; if you are adding an &lt;strong&gt;Expense&lt;/strong&gt;.&lt;br /&gt;
        ///    .
        /// </summary>
        internal static string Sheet_Input_Adding_Note_Amount_Label {
            get {
                return ResourceManager.GetString("Sheet.Input.Adding.Note.Amount.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    You can add as many elements as you want, either &lt;strong&gt;guests&lt;/strong&gt; or &lt;strong&gt;expenses&lt;/strong&gt; by tapping the &quot;plus&quot; button at the top right corner of the corresponding box.&lt;br /&gt;&lt;br /&gt;
        ///    This will popup a window that will, at its top, display the proper action that is taking place.&lt;br /&gt;&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; &quot;Add a guest&quot; if you tapped the button of the first box.&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; &quot;Add an expense&quot; if you tapped the button of the second box.&lt;br /&gt;
        ///    &lt;br /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Input_Adding_Part1 {
            get {
                return ResourceManager.GetString("Sheet.Input.Adding.Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    In any case the &lt;strong&gt;Name&lt;/strong&gt; field is required and the &lt;strong&gt;Contribution&lt;/strong&gt; or &lt;strong&gt;Value&lt;/strong&gt; can&apos;t have a negative number.&lt;br /&gt;&lt;br /&gt;
        ///    If you are adding an &lt;strong&gt;Expense&lt;/strong&gt; the value must be greater than 0.&lt;br /&gt;&lt;br /&gt;
        ///    Don&apos;t worry about remembering these rules. If you misfollow any of them a message will appear on top of the field guiding you to correct them.&lt;br /&gt;&lt;br /&gt;
        ///    Once the fields are properly set you may tap in the green circular button wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Input_Adding_Part2 {
            get {
                return ResourceManager.GetString("Sheet.Input.Adding.Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    The &lt;strong&gt;Input tab&lt;/strong&gt; is composed by two main groups:&lt;br /&gt;&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; &lt;strong&gt;Guests&lt;/strong&gt;&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; &lt;strong&gt;Expenses&lt;/strong&gt;&lt;br /&gt;
        ///    &lt;br /&gt;
        ///    You can see them as boxes vertically positioned in the content of the tab.&lt;br /&gt;&lt;br /&gt;
        ///    Each box, or group, has a header that describes what elements they represents (&quot;Guests&quot; or &quot;Expenses&quot;) followed by the number of elements added.&lt;br /&gt;&lt;br /&gt;
        ///    On the top right corner of each box there  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Input_Components {
            get {
                return ResourceManager.GetString("Sheet.Input.Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does this tab contain?.
        /// </summary>
        internal static string Sheet_Input_Components_Header {
            get {
                return ResourceManager.GetString("Sheet.Input.Components.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that no confirmation will be required when tapping the &quot;trash&quot; icon and this action cannot be undone..
        /// </summary>
        internal static string Sheet_Input_Edit_Delete_Note {
            get {
                return ResourceManager.GetString("Sheet.Input.Edit.Delete.Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I edit the information?.
        /// </summary>
        internal static string Sheet_Input_Edit_Header {
            get {
                return ResourceManager.GetString("Sheet.Input.Edit.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    At any time you may modify the event&apos;s information whether by editing an element or removing it.&lt;br /&gt;&lt;br /&gt;
        ///    For any case you can tap the item in the list and the same window used to add it will popup. This time the header of the window will display the name of the element and the fields will already be filled with the selected element&apos;s properties.&lt;br /&gt;&lt;br /&gt;
        ///    In case you&apos;re attempting to change the information you may tap the &quot;check&quot; button to save it just as you did when you previou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Input_Edit_Part1 {
            get {
                return ResourceManager.GetString("Sheet.Input.Edit.Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    Once completed the window will close and you may see the changes in the groups.&lt;br /&gt;&lt;br /&gt;
        ///    If you decide not to perform any changes (adding, editing or deleting) after the window popped you can tap the white circular button with an &quot;X&quot; icon in it, at the bottom center of the window to close it.
        ///    
        ///    .
        /// </summary>
        internal static string Sheet_Input_Edit_Part2 {
            get {
                return ResourceManager.GetString("Sheet.Input.Edit.Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    Represents any cost for the event that &lt;strong&gt;has not been payed for yet&lt;/strong&gt; and has been agreed upon to divide between the rest of the guests. &lt;br /&gt;&lt;br /&gt;
        ///    This could be the rent of a grill for a barbacue, a laser tag arena, a whole villa for the night, etc.
        ///    
        ///    .
        /// </summary>
        internal static string Sheet_Input_Guest_Expense_Definition_Expense_Description {
            get {
                return ResourceManager.GetString("Sheet.Input.Guest.Expense.Definition.Expense.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense:.
        /// </summary>
        internal static string Sheet_Input_Guest_Expense_Definition_Expense_Label {
            get {
                return ResourceManager.GetString("Sheet.Input.Guest.Expense.Definition.Expense.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    Represents any amount of money that a particular guest spent for this event and has been agreed upon to divide between the rest of the guests. &lt;br /&gt;&lt;br /&gt;
        ///    This could be food a guest brought for everyone, it could be beverages or even a Karaoke machine the guest rented for the night and has already payed for.
        ///    .
        /// </summary>
        internal static string Sheet_Input_Guest_Expense_Definition_Guest_Description {
            get {
                return ResourceManager.GetString("Sheet.Input.Guest.Expense.Definition.Guest.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest&apos;s contribution:.
        /// </summary>
        internal static string Sheet_Input_Guest_Expense_Definition_Guest_Label {
            get {
                return ResourceManager.GetString("Sheet.Input.Guest.Expense.Definition.Guest.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribution or expense?.
        /// </summary>
        internal static string Sheet_Input_Guest_Expense_Header {
            get {
                return ResourceManager.GetString("Sheet.Input.Guest.Expense.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    A common question would be when to add an expense or a guest&apos;s contribution. For that, first we need to know the definitions of each element.
        ///    .
        /// </summary>
        internal static string Sheet_Input_Guest_Expense_Part1 {
            get {
                return ResourceManager.GetString("Sheet.Input.Guest.Expense.Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main difference for calculating the outcome is that unlike a contribution, a new expense will increase the share, while a new contribution (a new guest) may result, depending on their contribution, in a decreasing of the share since is now divided between more guests..
        /// </summary>
        internal static string Sheet_Input_Guest_Expense_Part2 {
            get {
                return ResourceManager.GetString("Sheet.Input.Guest.Expense.Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input tab.
        /// </summary>
        internal static string Sheet_Input_Help_Topic {
            get {
                return ResourceManager.GetString("Sheet.Input.Help.Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed explanation of the input tab, its components and its usage..
        /// </summary>
        internal static string Sheet_Input_Help_Topic_Quick_Summary {
            get {
                return ResourceManager.GetString("Sheet.Input.Help.Topic.Quick.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    Whenever a box contains elements in it the empty message (read above) will be replaced by a &lt;strong&gt;list&lt;/strong&gt; and a &lt;strong&gt;footer&lt;/strong&gt;.&lt;br /&gt;&lt;br /&gt;
        ///    The &lt;strong&gt;list&lt;/strong&gt;, in the center of the box, contains two columns. At the left the name of the element and at the right its contribution or value.&lt;br /&gt;&lt;br /&gt;
        ///    The &lt;strong&gt;footer&lt;/strong&gt;, at the bottom of the box, will show the sum of the contributions or values of the elements.
        ///    
        ///    .
        /// </summary>
        internal static string Sheet_Input_Items_List {
            get {
                return ResourceManager.GetString("Sheet.Input.Items.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading the boxes or groups.
        /// </summary>
        internal static string Sheet_Input_Items_List_Header {
            get {
                return ResourceManager.GetString("Sheet.Input.Items.List.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    Yes. Whenever either boxes contain elements in them the button with an &quot;eraser&quot; icon in it at the top right of the screen, next to the menu button, can be tapped to delete all the information.&lt;br /&gt;&lt;br /&gt;
        ///    &lt;strong&gt;A dialog will appear asking you to confirm the operation since this action cannot be undone.&lt;/strong&gt;&lt;br /&gt;&lt;br /&gt;
        ///    This option will remain disabled whilst both boxes are empty.
        ///    .
        /// </summary>
        internal static string Sheet_Input_Reset {
            get {
                return ResourceManager.GetString("Sheet.Input.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I clear everything in one go?.
        /// </summary>
        internal static string Sheet_Input_Reset_Header {
            get {
                return ResourceManager.GetString("Sheet.Input.Reset.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    This tab allows you to enter the event information regarding guests and expenses.&lt;br /&gt;&lt;br /&gt;
        ///    All data you enter will automatically be stored in your device for you to resume your work at any time, even after the app is terminated or the device is restarted.&lt;br /&gt;&lt;br /&gt;
        ///    You can delete the complete stored data (input and app data) and start from scratch (as if &lt;strong&gt;RomanApp&lt;/strong&gt; has been reinstalled) by going to the &lt;strong&gt;Application Manager&lt;/strong&gt; in your device settings and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Input_Summary {
            get {
                return ResourceManager.GetString("Sheet.Input.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    In order to have a proper outcome we need to meet the minimum requirements to get it. If one of them are not met we will see a message informing us why we are not getting a detailed result:
        ///    .
        /// </summary>
        internal static string Sheet_Outcome_Empty {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least two guests to have the total of the event cost divided in shares..
        /// </summary>
        internal static string Sheet_Outcome_Empty_Enough_Guests_Description {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Empty.Enough.Guests.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8226; Not enough guests:.
        /// </summary>
        internal static string Sheet_Outcome_Empty_Enough_Guests_Label {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Empty.Enough.Guests.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is that exclamation mark?.
        /// </summary>
        internal static string Sheet_Outcome_Empty_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Empty.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After doing the calculations the outcome states that nobody should pay more than they already contributed..
        /// </summary>
        internal static string Sheet_Outcome_Empty_No_Debt_Description {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Empty.No.Debt.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8226; Nobody owes anything:.
        /// </summary>
        internal static string Sheet_Outcome_Empty_No_Debt_Label {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Empty.No.Debt.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total cost of the event (see &quot;Total&quot; in the &lt;strong&gt;Summary&lt;/strong&gt; section above) added up to zero..
        /// </summary>
        internal static string Sheet_Outcome_Empty_No_Total_Description {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Empty.No.Total.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8226; Total contributed must be greater than 0:.
        /// </summary>
        internal static string Sheet_Outcome_Empty_No_Total_Label {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Empty.No.Total.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    To fully understand how to read the outcome result we are going to run some examples. This can be verified entering the same values in the &lt;strong&gt;Input tab&lt;/strong&gt;.
        ///    
        ///    .
        /// </summary>
        internal static string Sheet_Outcome_Examples {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 1 (simple):.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example1_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example1.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    There are three people attending this event. Myself, John and Mike. &lt;br /&gt;&lt;br /&gt;
        ///    I contributed with nothing whilst John contributed &lt;strong&gt;64&lt;/strong&gt; for food and Mike &lt;strong&gt;86&lt;/strong&gt; for beverages.
        ///    
        ///    .
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example1_Premise {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example1.Premise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    The total spent for this event was &lt;strong&gt;150&lt;/strong&gt; (John&apos;s food for &lt;strong&gt;64&lt;/strong&gt; and Mike&apos;s beverages for &lt;strong&gt;86&lt;/strong&gt;). Divided by the 3 of us gives us a share of &lt;strong&gt;50&lt;/strong&gt;. That is what each guest is supposed to pay at the end of this event.&lt;br /&gt;&lt;br /&gt;
        ///    &lt;strong&gt;But...&lt;/strong&gt; John and Mike already contributed even more money than their share.&lt;br /&gt;&lt;br /&gt;
        ///    This means that in the outcome I will see myself owing money and John and Mike collecting.&lt;br /&gt;&lt;br / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example1_Result {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example1.Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 2 (medium):.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example2_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example2.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    This time will be using expenses.&lt;br/&gt;&lt;br/&gt;
        ///    Four people at this event: Myself, Chris, Susan and Lucy. &lt;br /&gt;&lt;br /&gt;
        ///    &lt;u&gt;Contributions (4):&lt;/u&gt;&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Myself&lt;/strong&gt;: 105&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Chris&lt;/strong&gt;: 0&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Susan&lt;/strong&gt;: 15&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Lucy&lt;/strong&gt;: 110&lt;br /&gt;
        ///    &lt;br /&gt;
        ///    We are now adding an expense for &lt;strong&gt;170&lt;/strong&gt;, let&apos;s say for the paintball gear, reloads and time will be using it. We decide to spli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example2_Premise {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example2.Premise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    The total cost of this event is &lt;strong&gt;400&lt;/strong&gt;. That is &lt;strong&gt;100&lt;/strong&gt; for each to pay &lt;strong&gt;(the Share)&lt;/strong&gt;. &lt;br /&gt;&lt;br /&gt;
        ///    &lt;strong&gt;230&lt;/strong&gt; will be for those who contributed (minus their share) and &lt;strong&gt;170&lt;/strong&gt; to pay for &quot;paintball&quot;.&lt;br /&gt;&lt;br /&gt;
        ///    Chris owes the total share of &lt;strong&gt;100&lt;/strong&gt;, Susan owes &lt;strong&gt;85&lt;/strong&gt; since she already contributed with &lt;strong&gt;15&lt;/strong&gt;.&lt;br /&gt;&lt;br /&gt;
        ///    Lucy and I will be collecting from what Chris and Susan  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example2_Result {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example2.Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 3 (advanced):.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example3_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example3.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    In this example will try to get the use of all three groups of the outcome. &lt;br /&gt;&lt;br /&gt;
        ///    Four people at this event: Myself, Ellen, Leo and Jo. &lt;br /&gt;&lt;br /&gt;
        ///    &lt;u&gt;Contributions (4):&lt;/u&gt;&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Myself&lt;/strong&gt;: 5 (snacks)&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Ellen&lt;/strong&gt;: 30 (beverages)&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Leo&lt;/strong&gt;: 25 (more snacks)&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Jo&lt;/strong&gt;: 0&lt;br /&gt;
        ///    &lt;br /&gt;
        ///    &lt;u&gt;Expenses (2):&lt;/u&gt;&lt;br /&gt;
        ///    &amp;#8226; &lt;strong&gt;Tennis court&lt;/strong&gt;: 3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example3_Premise {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example3.Premise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    The total cost of this event is &lt;strong&gt;100&lt;/strong&gt;. That is &lt;strong&gt;25&lt;/strong&gt; for each to pay &lt;strong&gt;(the Share)&lt;/strong&gt;. &lt;br /&gt;&lt;br /&gt;
        ///    Jo and I are the ones who should put money on the table. I should pay &lt;strong&gt;20&lt;/strong&gt; since &lt;strong&gt;5&lt;/strong&gt; were already covered for snacks and Jo should pay her full share.&lt;br /&gt;&lt;br /&gt;
        ///    A total of &lt;strong&gt;45&lt;/strong&gt; is now on the table. &lt;strong&gt;5&lt;/strong&gt; goes to Ellen since she contributed with &lt;strong&gt;30&lt;/strong&gt;.&lt;br /&gt;&lt;br /&gt;
        ///    We are [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Example3_Result {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Example3.Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s take a look at some examples.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the result?.
        /// </summary>
        internal static string Sheet_Outcome_Examples_Result {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Examples.Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    Along with the &lt;strong&gt;Summary&lt;/strong&gt; the outcome provides three different boxes which represent the event&apos;s guests sorted in three groups:&lt;br /&gt;&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; Those who owe.&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; Those who must collect&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; Those who broke even&lt;br /&gt;
        ///    &lt;br /&gt;
        ///    Each box has a header that describes, at its left side, what group of guests (described above) contains and  the count of guests at its right side.&lt;br /&gt;&lt;br /&gt;
        ///    Inside the b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Outcome_Groups {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s in the box?.
        /// </summary>
        internal static string Sheet_Outcome_Groups_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Groups.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    You may notice that not all the groups are always shown. This is because the outcome only shows those which contain at least one guest after doing the calculations. For example if the outcome states that no guests should collect an amount but all of them should pay at least a part of their share, the second group (&quot;Who must collect?&quot;) will not be shown.
        ///    .
        /// </summary>
        internal static string Sheet_Outcome_Groups_Note_Visible {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Groups.Note.Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome tab.
        /// </summary>
        internal static string Sheet_Outcome_Help_Topic {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Help.Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed explanation of how to read the outcome of an event calculation..
        /// </summary>
        internal static string Sheet_Outcome_Help_Topic_Quick_Summary {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Help.Topic.Quick.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the coefficient between the total amount and the number of guests. The share is what each guest is &lt;strong&gt;supposed&lt;/strong&gt; to pay..
        /// </summary>
        internal static string Sheet_Outcome_Summary_Share_Description {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Share.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of all guest&apos;s contributions and expenses. &lt;strong&gt;This number represents the entire cost of the event.&lt;/strong&gt;.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Total_Description {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Total.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of all expenses..
        /// </summary>
        internal static string Sheet_Outcome_Summary_Total_Expenses_Description {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Total.Expenses.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    Another way to read the result is by tapping the button with the &quot;conversation&quot; icon in it at the bottom of the tab.&lt;br /&gt;
        ///   This will popup a window explaining step by step the calculation result and what to do with the money.
        ///    
        ///    .
        /// </summary>
        internal static string Sheet_Outcome_Text {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain it to me like I&apos;m 5..
        /// </summary>
        internal static string Sheet_Outcome_Text_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    At the top of the tab there is a box that shows a quick summary of the calculations:
        ///    .
        /// </summary>
        internal static string Sheet_Outcome_Totals {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Sheet_Outcome_Totals_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Totals.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8226; Share:.
        /// </summary>
        internal static string Sheet_Outcome_Totals_Share_Label {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Totals.Share.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of all guests&apos; contributions, those which are greater than zero..
        /// </summary>
        internal static string Sheet_Outcome_Totals_Total_Contributions_Description {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Totals.Total.Contributions.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8226; Total contributions:.
        /// </summary>
        internal static string Sheet_Outcome_Totals_Total_Contributions_Label {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Totals.Total.Contributions.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8226; Total expenses:.
        /// </summary>
        internal static string Sheet_Outcome_Totals_Total_Expenses_Label {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Totals.Total.Expenses.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8226; Total:.
        /// </summary>
        internal static string Sheet_Outcome_Totals_Total_Label {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Totals.Total.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    This tab will give you the result calculation of every guest&apos;s contribution and expense.
        ///    .
        /// </summary>
        internal static string Sheet_Output_Summary {
            get {
                return ResourceManager.GetString("Sheet.Output.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main panel.
        /// </summary>
        internal static string Sheet_Overview_Help_Topic {
            get {
                return ResourceManager.GetString("Sheet.Overview.Help.Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A first glace of the main panel..
        /// </summary>
        internal static string Sheet_Overview_Help_Topic_Quick_Summary {
            get {
                return ResourceManager.GetString("Sheet.Overview.Help.Topic.Quick.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on how to work with this portion of the panel check the &lt;strong&gt;Input Tab&lt;/strong&gt; link in the &lt;strong&gt;&quot;See Also&quot;&lt;/strong&gt; section below..
        /// </summary>
        internal static string Sheet_Overview_Summary_Note_Input {
            get {
                return ResourceManager.GetString("Sheet.Overview.Summary.Note.Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on how to read the outcome calculation check the &lt;strong&gt;Outcome Tab&lt;/strong&gt; link in the &lt;strong&gt;&quot;See Also&quot;&lt;/strong&gt; section below..
        /// </summary>
        internal static string Sheet_Overview_Summary_Note_Outcome {
            get {
                return ResourceManager.GetString("Sheet.Overview.Summary.Note.Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    The &lt;strong&gt;Main panel&lt;/strong&gt; is where you will spend most of the time using the app.&lt;br /&gt;
        ///    Here you will be able to input the event&apos;s information and see the result in real time.&lt;br /&gt;&lt;br /&gt;
        ///    The event&apos;s information consists of two type of elements:&lt;br /&gt;&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; &lt;strong&gt;Guests&lt;/strong&gt;&lt;br /&gt;
        ///    &amp;nbsp;&amp;nbsp;&amp;#8226; &lt;strong&gt;Expenses&lt;/strong&gt;&lt;br /&gt;
        ///    &lt;br /&gt;
        ///    The &lt;strong&gt;guests&lt;/strong&gt; are the people attending the event. Each one is identified by their n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sheet_Overview_Summary_Part1 {
            get {
                return ResourceManager.GetString("Sheet.Overview.Summary.Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///    At any time during the event you may add, edit and remove any element (&lt;strong&gt;guests&lt;/strong&gt; and/or &lt;strong&gt;expenses&lt;/strong&gt;) which will be composing the total cost of the event. At the same time the app will calculate how much money should some guests pay to cover the cost of the event and how much money should other guests collect from that to cover their difference of the share.
        ///    
        ///    .
        /// </summary>
        internal static string Sheet_Overview_Summary_Part2 {
            get {
                return ResourceManager.GetString("Sheet.Overview.Summary.Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      This panel will allow you to configure different aspects and behaviours of the app. All changes will be immediately saved at the moment you change them and will remain even after the app is terminated or your device is restarted.
        ///    .
        /// </summary>
        internal static string Sheet_Settings {
            get {
                return ResourceManager.GetString("Sheet.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Sheet_Settings_Help_Topic {
            get {
                return ResourceManager.GetString("Sheet.Settings.Help.Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition of each configuration property. Their purpose and their impact in the app..
        /// </summary>
        internal static string Sheet_Settings_Help_Topic_Quick_Summary {
            get {
                return ResourceManager.GetString("Sheet.Settings.Help.Topic.Quick.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8226; Use whole numbers?.
        /// </summary>
        internal static string Sheet_Settings_Option_Whole_Label {
            get {
                return ResourceManager.GetString("Sheet.Settings.Option.Whole.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the app to use whole numbers or decimals. In case is set for the latter (&lt;strong&gt;Off&lt;/strong&gt;) the app will round the decimals in intervals of 25, 50 and 75 to make it easier for the guests to pay their share..
        /// </summary>
        internal static string Sheet_Settings_Option_Whole_Line1 {
            get {
                return ResourceManager.GetString("Sheet.Settings.Option.Whole.Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Sheet_Settings_Options_Header {
            get {
                return ResourceManager.GetString("Sheet.Settings.Options.Header", resourceCulture);
            }
        }
    }
}
