//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomanApp.Client.Mobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RomanApp.Client.Mobile.Resx.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About RomanApp.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help_Title {
            get {
                return ResourceManager.GetString("Help.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I help you with?.
        /// </summary>
        internal static string HelpIndex_Header {
            get {
                return ResourceManager.GetString("HelpIndex.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help index.
        /// </summary>
        internal static string HelpIndex_Title {
            get {
                return ResourceManager.GetString("HelpIndex.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_General_Title {
            get {
                return ResourceManager.GetString("Settings.General.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use whole numbers.
        /// </summary>
        internal static string Settings_General_Whole {
            get {
                return ResourceManager.GetString("Settings.General.Whole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expenses added.
        /// </summary>
        internal static string Sheet_Card_Empty_Expenses {
            get {
                return ResourceManager.GetString("Sheet.Card.Empty.Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guests added.
        /// </summary>
        internal static string Sheet_Card_Empty_Guests {
            get {
                return ResourceManager.GetString("Sheet.Card.Empty.Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Sheet_Card_Expenses_Header {
            get {
                return ResourceManager.GetString("Sheet.Card.Expenses.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Sheet_Card_Footer_Label {
            get {
                return ResourceManager.GetString("Sheet.Card.Footer.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Sheet_Card_Header_Expenses {
            get {
                return ResourceManager.GetString("Sheet.Card.Header.Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        internal static string Sheet_Card_Header_Guests {
            get {
                return ResourceManager.GetString("Sheet.Card.Header.Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Sheet_Dialog_Reset_Action_No {
            get {
                return ResourceManager.GetString("Sheet.Dialog.Reset.Action.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Sheet_Dialog_Reset_Action_Yes {
            get {
                return ResourceManager.GetString("Sheet.Dialog.Reset.Action.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Sheet_Dialog_Reset_Header {
            get {
                return ResourceManager.GetString("Sheet.Dialog.Reset.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the sheet?.
        /// </summary>
        internal static string Sheet_Dialog_Reset_Verbiage {
            get {
                return ResourceManager.GetString("Sheet.Dialog.Reset.Verbiage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Edit_Expense_Amount {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Edit.Expense.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribution.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Edit_Guest_Amount {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Edit.Guest.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Edit_Name {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Edit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Header_Expense {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Header.Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add guest.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Header_Guest {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Header.Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit expense.
        /// </summary>
        internal static string Sheet_Input_Dialog_Edit_Header_Expense {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Edit.Header.Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit guest.
        /// </summary>
        internal static string Sheet_Input_Dialog_Edit_Header_Guest {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Edit.Header.Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Sheet_Navigation_Reset {
            get {
                return ResourceManager.GetString("Sheet.Navigation.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Sheet_Navigation_Settings {
            get {
                return ResourceManager.GetString("Sheet.Navigation.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who must collect?.
        /// </summary>
        internal static string Sheet_Outcome_Group_Creditors_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Group.Creditors.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who owes?.
        /// </summary>
        internal static string Sheet_Outcome_Group_Debtors_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Group.Debtors.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who owes nothing?.
        /// </summary>
        internal static string Sheet_Outcome_Group_Even_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Group.Even.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Share {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Total {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total expenses.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Total_Expenses {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Total.Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total contributions.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Total_Guests {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Total.Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody owes anything.
        /// </summary>
        internal static string Sheet_Outcome_Unavailable_No_Debtors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Unavailable.No.Debtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough guests.
        /// </summary>
        internal static string Sheet_Outcome_Unavailable_No_Guests {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Unavailable.No.Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total contributed must be greater than 0.
        /// </summary>
        internal static string Sheet_Outcome_Unavailable_No_Total {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Unavailable.No.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        internal static string Sheet_Tab_Input_Title {
            get {
                return ResourceManager.GetString("Sheet.Tab.Input.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Sheet_Tab_Outcome_Title {
            get {
                return ResourceManager.GetString("Sheet.Tab.Outcome.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RomanApp.
        /// </summary>
        internal static string Sheet_Title {
            get {
                return ResourceManager.GetString("Sheet.Title", resourceCulture);
            }
        }
    }
}
