//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomanApp.Client.Mobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RomanApp.Client.Mobile.Resx.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        internal static string About_All_Rights {
            get {
                return ResourceManager.GetString("About.All.Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string About_App_Version {
            get {
                return ResourceManager.GetString("About.App.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components and tools.
        /// </summary>
        internal static string About_Libraries {
            get {
                return ResourceManager.GetString("About.Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android specification.
        /// </summary>
        internal static string About_Mobile {
            get {
                return ResourceManager.GetString("About.Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Android Version.
        /// </summary>
        internal static string About_Mobile_Android_Min {
            get {
                return ResourceManager.GetString("About.Mobile.Android.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Android Version.
        /// </summary>
        internal static string About_Mobile_Android_Target {
            get {
                return ResourceManager.GetString("About.Mobile.Android.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Bustos Adrian.
        /// </summary>
        internal static string About_Owner {
            get {
                return ResourceManager.GetString("About.Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About RomanApp.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RomanApp.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help_Title {
            get {
                return ResourceManager.GetString("Help.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I help you with?.
        /// </summary>
        internal static string HelpIndex_Header {
            get {
                return ResourceManager.GetString("HelpIndex.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help index.
        /// </summary>
        internal static string HelpIndex_Title {
            get {
                return ResourceManager.GetString("HelpIndex.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment please....
        /// </summary>
        internal static string MainPage_Loading {
            get {
                return ResourceManager.GetString("MainPage.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use numeric keyboard.
        /// </summary>
        internal static string Settings_General_Numeric {
            get {
                return ResourceManager.GetString("Settings.General.Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_General_Title {
            get {
                return ResourceManager.GetString("Settings.General.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use whole numbers.
        /// </summary>
        internal static string Settings_General_Whole {
            get {
                return ResourceManager.GetString("Settings.General.Whole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expenses added.
        /// </summary>
        internal static string Sheet_Card_Empty_Expenses {
            get {
                return ResourceManager.GetString("Sheet.Card.Empty.Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guests added.
        /// </summary>
        internal static string Sheet_Card_Empty_Guests {
            get {
                return ResourceManager.GetString("Sheet.Card.Empty.Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Sheet_Card_Expenses_Header {
            get {
                return ResourceManager.GetString("Sheet.Card.Expenses.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Sheet_Card_Footer_Label {
            get {
                return ResourceManager.GetString("Sheet.Card.Footer.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Sheet_Card_Header_Expenses {
            get {
                return ResourceManager.GetString("Sheet.Card.Header.Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        internal static string Sheet_Card_Header_Guests {
            get {
                return ResourceManager.GetString("Sheet.Card.Header.Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Sheet_Dialog_Reset_Action_No {
            get {
                return ResourceManager.GetString("Sheet.Dialog.Reset.Action.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Sheet_Dialog_Reset_Action_Yes {
            get {
                return ResourceManager.GetString("Sheet.Dialog.Reset.Action.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Sheet_Dialog_Reset_Header {
            get {
                return ResourceManager.GetString("Sheet.Dialog.Reset.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the sheet?.
        /// </summary>
        internal static string Sheet_Dialog_Reset_Verbiage {
            get {
                return ResourceManager.GetString("Sheet.Dialog.Reset.Verbiage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Edit_Expense_Amount {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Edit.Expense.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribution.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Edit_Guest_Amount {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Edit.Guest.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Edit_Name {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Edit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Header_Expense {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Header.Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add guest.
        /// </summary>
        internal static string Sheet_Input_Dialog_Add_Header_Guest {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Add.Header.Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit expense.
        /// </summary>
        internal static string Sheet_Input_Dialog_Edit_Header_Expense {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Edit.Header.Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit guest.
        /// </summary>
        internal static string Sheet_Input_Dialog_Edit_Header_Guest {
            get {
                return ResourceManager.GetString("Sheet.Input.Dialog.Edit.Header.Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Sheet_Navigation_Reset {
            get {
                return ResourceManager.GetString("Sheet.Navigation.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Sheet_Navigation_Settings {
            get {
                return ResourceManager.GetString("Sheet.Navigation.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in mind that since the app is set to use whole numbers all figures are rounded. For a more accurate result go to &lt;strong&gt;Settings&lt;/strong&gt; and turn off the option &lt;i&gt;&quot;Use whole numbers&quot;&lt;/i&gt;..
        /// </summary>
        internal static string Sheet_Outcome_Disclaimer {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who must collect?.
        /// </summary>
        internal static string Sheet_Outcome_Group_Creditors_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Group.Creditors.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who owes?.
        /// </summary>
        internal static string Sheet_Outcome_Group_Debtors_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Group.Debtors.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who owes nothing?.
        /// </summary>
        internal static string Sheet_Outcome_Group_Even_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Group.Even.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses to cover.
        /// </summary>
        internal static string Sheet_Outcome_Group_Expenses_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Group.Expenses.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Sheet_Outcome_Group_Total {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Group.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to the figures being rounded  we are missing &lt;strong&gt;{leftOver}&lt;/strong&gt;.
        /// </summary>
        internal static string Sheet_Outcome_LeftOver_Shortcoming {
            get {
                return ResourceManager.GetString("Sheet.Outcome.LeftOver.Shortcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to the figures being rounded we are with a surplus of &lt;strong&gt;{leftOver}&lt;/strong&gt;.
        /// </summary>
        internal static string Sheet_Outcome_LeftOver_Surplus {
            get {
                return ResourceManager.GetString("Sheet.Outcome.LeftOver.Surplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Share {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Total {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total expenses.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Total_Expenses {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Total.Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total contributions.
        /// </summary>
        internal static string Sheet_Outcome_Summary_Total_Guests {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Summary.Total.Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying up....
        /// </summary>
        internal static string Sheet_Outcome_Text_Collected_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.Collected.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{value}&lt;/strong&gt; should go to &lt;i&gt;{name}&lt;/i&gt;.
        /// </summary>
        internal static string Sheet_Outcome_Text_CollectedCreditor {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.CollectedCreditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From that {creditors}..
        /// </summary>
        internal static string Sheet_Outcome_Text_CollectedManyDebtorsCreditors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.CollectedManyDebtorsCreditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That money should go to &lt;i&gt;{singleCreditor}&lt;/i&gt;..
        /// </summary>
        internal static string Sheet_Outcome_Text_CollectedOneSingleCreditor {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.CollectedOneSingleCreditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From &lt;i&gt;{singleDebtor}&lt;/i&gt;&apos;s share, {creditors}.
        /// </summary>
        internal static string Sheet_Outcome_Text_CollectedSingleDebtor {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.CollectedSingleDebtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {debtors} pay their share, there should be &lt;strong&gt;{totalCollected}&lt;/strong&gt; on the table..
        /// </summary>
        internal static string Sheet_Outcome_Text_CollectedTotalCollected {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.CollectedTotalCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;&amp;nbsp;&amp;#8226; &lt;i&gt;{name}&lt;/i&gt;&apos;s share is &lt;strong&gt;{debt}&lt;/strong&gt; since they already contributed with &lt;strong&gt;{contribution}&lt;/strong&gt;..
        /// </summary>
        internal static string Sheet_Outcome_Text_DebtorsEachPartialDebtor {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.DebtorsEachPartialDebtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {fullDebtors} should put &lt;strong&gt;{share}&lt;/strong&gt; (the full share) on the table..
        /// </summary>
        internal static string Sheet_Outcome_Text_DebtorsFullDebtorsPlural {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.DebtorsFullDebtorsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {fullDebtors} should put &lt;strong&gt;{share}&lt;/strong&gt; (the full share) on the table..
        /// </summary>
        internal static string Sheet_Outcome_Text_DebtorsFullDebtorsSingular {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.DebtorsFullDebtorsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead {partialDebtors} should pay less than their full share, since they already contributed for this event..
        /// </summary>
        internal static string Sheet_Outcome_Text_DebtorsInsteadPartialDebtorsPlural {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.DebtorsInsteadPartialDebtorsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead &lt;i&gt;{name}&lt;/i&gt; should put &lt;strong&gt;{debt}&lt;/strong&gt; on the table since they already contributed for the event with &lt;strong&gt;{contribution}&lt;/strong&gt;..
        /// </summary>
        internal static string Sheet_Outcome_Text_DebtorsInsteadPartialDebtorsSingular {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.DebtorsInsteadPartialDebtorsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {partialDebtors} should pay less than their full share, since they already contributed for this event..
        /// </summary>
        internal static string Sheet_Outcome_Text_DebtorsPartialDebtorsPlural {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.DebtorsPartialDebtorsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;{name}&lt;/i&gt; should put &lt;strong&gt;{debt}&lt;/strong&gt; on the table since they already contributed for the event with &lt;strong&gt;{contribution}&lt;/strong&gt;..
        /// </summary>
        internal static string Sheet_Outcome_Text_DebtorsPartialDebtorsSingular {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.DebtorsPartialDebtorsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What about the rest?.
        /// </summary>
        internal static string Sheet_Outcome_Text_Evens_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.Evens.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And finally {evens} should not pay anything since their contributions matches their share..
        /// </summary>
        internal static string Sheet_Outcome_Text_EvensPlural {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.EvensPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And finally {evens} should not pay anything since their contribution matches their share..
        /// </summary>
        internal static string Sheet_Outcome_Text_EvensSingular {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.EvensSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covering expenses....
        /// </summary>
        internal static string Sheet_Outcome_Text_Expenses_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.Expenses.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{value}&lt;/strong&gt; for &lt;u&gt;{name}&lt;/u&gt;.
        /// </summary>
        internal static string Sheet_Outcome_Text_ExpensesExpense {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ExpensesExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This money is to pay {expenses}..
        /// </summary>
        internal static string Sheet_Outcome_Text_ExpensesExpenses {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ExpensesExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We still have &lt;strong&gt;{remaining}&lt;/strong&gt; remaining on the table..
        /// </summary>
        internal static string Sheet_Outcome_Text_ExpensesRemaining {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ExpensesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... and we are done!.
        /// </summary>
        internal static string Sheet_Outcome_Text_Footer {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, so....
        /// </summary>
        internal static string Sheet_Outcome_Text_Header {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll notice there are &lt;strong&gt;{leftOver}&lt;/strong&gt; missing. You&apos;ll have to decide who should cover this difference..
        /// </summary>
        internal static string Sheet_Outcome_Text_LeftOver_Shortcoming {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.LeftOver.Shortcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll notice there are &lt;strong&gt;{leftOver}&lt;/strong&gt; left over. You can divide this between the guests as you see fit..
        /// </summary>
        internal static string Sheet_Outcome_Text_LeftOver_Surplus {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.LeftOver.Surplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But not all guests should pay and not all guests should pay their full share..
        /// </summary>
        internal static string Sheet_Outcome_Text_ShareCreditorsAndPartialDebtors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ShareCreditorsAndPartialDebtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be divided by the {guestsCount} guests giving us a share (what each guest is supposed to pay) of &lt;strong&gt;{share}&lt;/strong&gt;..
        /// </summary>
        internal static string Sheet_Outcome_Text_ShareDivided {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ShareDivided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But not all guests should pay..
        /// </summary>
        internal static string Sheet_Outcome_Text_ShareNoCreditors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ShareNoCreditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But not all guests should pay their full share..
        /// </summary>
        internal static string Sheet_Outcome_Text_SharePartialDebtors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.SharePartialDebtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;This is a rounded number from &lt;strong&gt;{realShare}&lt;/strong&gt;. So you might end up with a small difference at the end.&lt;/i&gt;.
        /// </summary>
        internal static string Sheet_Outcome_Text_ShareRealShare {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ShareRealShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyway, but not all guests should pay and not all guests should pay their full share..
        /// </summary>
        internal static string Sheet_Outcome_Text_ShareRealShareCreditorsAndPartialDebtors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ShareRealShareCreditorsAndPartialDebtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyway, but not all guests should pay..
        /// </summary>
        internal static string Sheet_Outcome_Text_ShareRealShareNoCreditors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ShareRealShareNoCreditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyway, but not all guests should pay their full share..
        /// </summary>
        internal static string Sheet_Outcome_Text_ShareRealSharePartialDebtors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.ShareRealSharePartialDebtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is composed by the guests&apos; contributions (&lt;strong&gt;{totalGuests}&lt;/strong&gt; in total) plus {expenses}..
        /// </summary>
        internal static string Sheet_Outcome_Text_TotalComponsed {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.TotalComponsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total cost of the event is &lt;strong&gt;{total}&lt;/strong&gt;..
        /// </summary>
        internal static string Sheet_Outcome_Text_TotalCostEvent {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.TotalCostEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{value}&lt;/strong&gt; for &lt;u&gt;{name}&lt;/u&gt;.
        /// </summary>
        internal static string Sheet_Outcome_Text_TotalExpense {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Text.TotalExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody owes anything.
        /// </summary>
        internal static string Sheet_Outcome_Unavailable_No_Debtors {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Unavailable.No.Debtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough guests.
        /// </summary>
        internal static string Sheet_Outcome_Unavailable_No_Guests {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Unavailable.No.Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total cost of the event must be greater than 0.
        /// </summary>
        internal static string Sheet_Outcome_Unavailable_No_Total {
            get {
                return ResourceManager.GetString("Sheet.Outcome.Unavailable.No.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        internal static string Sheet_Tab_Input_Title {
            get {
                return ResourceManager.GetString("Sheet.Tab.Input.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Sheet_Tab_Outcome_Title {
            get {
                return ResourceManager.GetString("Sheet.Tab.Outcome.Title", resourceCulture);
            }
        }
    }
}
